export type CommandBlockStatus = 'pending' | 'running' | 'success' | 'error';

export interface CommandBlock {
  /** Unique id generated by Rust backend (e.g. "blk-1714400000-1") */
  id: string;
  /** PTY session this block belongs to */
  sessionId: string;
  /** The raw command text entered by the user */
  command: string;
  /** Accumulated stdout/stderr output */
  output: string;
  /** Current execution status */
  status: CommandBlockStatus;
  /** Process exit code (null while running/pending) */
  exitCode: number | null;
  /** ISO timestamp when execution started */
  startedAt: string | null;
  /** ISO timestamp when execution completed */
  completedAt: string | null;
}

/** Payload emitted by Rust: block-cmd-started */
export interface BlockCmdStartedPayload {
  session_id: string;
  command_id: string;
}

/** Payload emitted by Rust: block-cmd-completed */
export interface BlockCmdCompletedPayload {
  session_id: string;
  command_id: string;
  exit_code: number;
}
