/** Status of a single task step */
export type TaskStatus = 'pending' | 'running' | 'success' | 'error' | 'skipped';

/** A single executable task step generated by AI */
export interface TaskItem {
  /** Unique id, e.g. "task-1714400000-0" */
  id: string;
  /** Human-readable description from AI */
  description: string;
  /** Shell command to execute */
  command: string;
  /** Current execution status */
  status: TaskStatus;
  /** Accumulated output (stdout + stderr) */
  output: string;
  /** Process exit code */
  exitCode: number | null;
  /** Error message if failed */
  error: string | null;
}

/** A group of tasks generated from a single AI query */
export interface TaskGroup {
  /** Unique id, e.g. "grp-1714400000" */
  id: string;
  /** Original natural language query from user */
  query: string;
  /** PTY session to execute commands in */
  sessionId: string;
  /** Ordered list of task steps */
  tasks: TaskItem[];
  /** Timestamp when created */
  createdAt: string;
  /** Whether the queue is paused (auto-pauses on failure) */
  paused: boolean;
}

/** Generate a unique task group id */
export function generateGroupId(): string {
  return `grp-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
}

/** Generate a unique task item id */
export function generateTaskId(index: number): string {
  return `task-${Date.now()}-${index}`;
}
